server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8001
              predicates:
                - Path=/users/**,/account/**

            - id: scooter-service
              uri: http://localhost:8004
              predicates:
                - Path=/scooter/**

            - id: journeys-service
              uri: http://localhost:8002
              predicates:
                - Path=/journey/**,/rate/**

            - id: maintenance-service
              uri: http://localhost:8003
              predicates:
                - Path=/maintenance/**

            - id: movement-service
              uri: http://localhost:8005
              predicates:
                - Path=/movement/**

            - id: parking-dock-service
              uri: http://localhost:8000
              predicates:
                - Path=/parkingdock/**


      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
eureka:
  client:
    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet: DEBUG
